task:
  only_if: $CIRRUS_TAG == ''
  matrix:
    - name: linux-amd64
      container:
        image: family/docker-builder
        platform: linux
        cpu: 4
        memory: 12G
        kvm: true
    - name: linux-arm64
      arm_container:
        image: family/docker-builder-arm64
        platform: linux
        cpu: 4
        memory: 12G
        kvm: true
  setup_script:
    - docker version
