amd64_docker_builder:
  only_if: $CIRRUS_TAG == ''
  setup_script:
    - docker version

arm64_docker_builder:
  only_if: $CIRRUS_TAG == ''
  env:
    CIRRUS_ARCH: arm64
  setup_script:
    - docker version
