docker_builder:
  only_if: $CIRRUS_TAG == ''
  # name: linux-arm64
  build_script:
  - docker version

docker_builder:
  # name: linux-arm64
  only_if: $CIRRUS_TAG == ''
  env:
    CIRRUS_ARCH: arm64
  build_script:
  - docker version
