task:
  only_if: $CIRRUS_TAG == ''
  matrix:
    - name: linux-amd64
      docker_builder:
        platform: linux
        image: docker:latest
    - name: linux-arm64
      arm_docker_builder:
        platform: linux
        image: docker:latest
  setup_script:
    - docker version
