task:
  only_if: $CIRRUS_TAG == ''
  timeout_in: 120m
  matrix:
    - name: linux-amd64
      container:
        image: docker:latest
        platform: linux
    - name: linux-arm64
      arm_container:
        image: docker:latest
        platform: linux
  setup_script:
    - docker version
